Update cd.yaml

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -17,8 +17,9 @@ jobs:
         USER: ${{ secrets.EC2_USER }}
       run: |
         echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
-        /usr/bin/docker version || echo "Docker not found"
         ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
+          /usr/bin/docker version || echo "Docker not found"
+          sudo usermod -aG ubuntu
           docker pull bandhan99/newz_shortie:${{ github.sha }}
           docker stop shortie-container || true
           docker rm shortie-container || true
